name = "Create-Ive Cogs Season 5"
author = "Canada_LaVearn and Herr Katze"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94c86ff0d02b25a01608464817b3cf9f4dca001fac50567bed7a18cbbc5faeb5"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
