name = "Season 6 1.20"
author = "Maple Modworks"
version = "0.0.10 HF 1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bad41d517ab5ee39e967aa649e03d4778c14c8dd5f372a285daab6ab752bb9ea"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
