name = "Season 6 1.20"
author = "Maple Modworks"
version = "473a378"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a90014491e3a37decbd2acd7fda98d4d047154d7f29408f200e7256b397abab2"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
