name = "Season 6 1.20"
author = "Maple Modworks"
version = "c70d36b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d73270d8c20600165cc22e629a3e71ce2f399e7f9393cbe942561da64ded77f"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
