name = "Season 6 1.20"
author = "Maple Modworks"
version = "83b86ad"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5d7b04f82806ae2c5b56845fdb33dbae03f6dd019b9849f592fc1a5698642c5"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
