name = "Season 6 1.20"
author = "Maple Modworks"
version = "42fdf5d"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b45fd47112954db1dbdc8e289ac153d8b854b43780414c6eb4932959699ea74c"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
