]name = "Create-Ive Cogs Season 6"
author = "Canada_LaVearn and Herr Katze"
version = "0.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fab7b54e705107c378f1d92c32b8cc6179643f3e55cd302eff87f3d7f2a658c4"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
