name = "Season 6 1.20"
author = "Maple Modworks"
version = "f85515f"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f85b614caa6969756b25a2b1df842f05ee2d20efa775c5454dd1692cd01fcfc7"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
