name = "Season 6 1.20"
author = "Maple Modworks"
version = "2daa7dd"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cff108431c255f1e7c7ca7e42490d17c3638f8d2814f34b9b731b0d6bea257c4"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
