name = "Season 6 1.20"
author = "Maple Modworks"
version = "0.0.8 HF 3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc3bcf58bca6614a1ca5254ac85eef5bdb3b847e5735563ea8f5c359c2bbdba7"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
