name = "Season 6 1.20"
author = "Maple Modworks"
version = "8dbe4c6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a59d1d498d692efe26630093589f9a414a180329f55d455881bd638fa82f40b2"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
