name = "Season 6 1.20"
author = "Maple Modworks"
version = "07a19c1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c9b08060aaf91bcaf78ee88dd2a27e40d8b084c186c1d7f97eb77fef8373c6b"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
