name = "Season 6 1.20"
author = "Maple Modworks"
version = "0.0.7 HF 1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91962ba68df0b2f635a12310eed0fc6e738a529620a34938507aef8e25988087"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
