name = "Season 6 1.20"
author = "Maple Modworks"
version = "dce9caf"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4942ed8882827e1b124dc701c325987e6713c40c9b659dd0f8632c6571ce6b10"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
