name = "Season 6 1.20"
author = "Maple Modworks"
version = "b61f616"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14660d768a5bc0be8a17b5a68aecccf057fd7be195f9be6f377af1075e09d81b"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
