name = "Create-Ive Cogs Season 6"
author = "Canada_LaVearn and Herr Katze"
version = "0.0.2 HOTFIX 1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74ef733e110269219f428e012c8b8c355d860850bfeec0ee83b9addade0101cd"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
