name = "Season 6 1.20"
author = "Maple Modworks"
version = "b6e871e"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93f1ef03cb96b909251e3da36d0ae44582673a8071974f543b6d90ef6f101b54"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
