name = "Season 6 1.20"
author = "Maple Modworks"
version = "0.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2802375cce6457adaad4ac3736329d2cc00b3f0a06ee689b2509fbe74927ea3"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
