name = "Season 6 1.20"
author = "Maple Modworks"
version = "b228fca"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c747510b97876ae6aeb1c8b95cbf7e89f2fd903315989ccc2d71480bcdfa4379"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
