name = "Season 6 1.20"
author = "Maple Modworks"
version = "a777ba2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0d3e83f548b8bf08d7b7d13843ee0a316545d50c2f2ae064209f66384bca5e9"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
