name = "Season 6 1.20"
author = "Maple Modworks"
version = "d0e1d0b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37105703472b5961c90cb08ebefa272bc5024bb58db0d3b45b668238277c391a"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
