name = "Season 6 1.20"
author = "Maple Modworks"
version = "a74efb0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "667513c835f472ebe50cc2c19c7ad37af6808993af3186defe2b93c3f62de790"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
