name = "Season 6 1.20"
author = "Maple Modworks"
version = "c70d36b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37e5376d5a5e26868b2f776cec83e39d9b12f6db77109932c0b79e5184de4c7c"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
