name = "Season 6 1.20"
author = "Maple Modworks"
version = "c38fec4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16c968f7d45348c32f4558e22e245cd35f806ce6326ecdba8eb588259f8ec0da"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
