name = "Season 6 1.20"
author = "Maple Modworks"
version = "c1c5082"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7600fb74211128ba380b86d2b2eb301a38c712e778b6b098afc483279a8265c"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
