name = "Season 6 1.20"
author = "Maple Modworks"
version = "fdefa32"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6735385f76383fd10827ce5594517cb990e7d23b93f4a744ef806aa278a2b6e4"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
