name = "Season 6 1.20"
author = "Maple Modworks"
version = "a077dde"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3a0839285d1d2e0409a2d9bca3295a669ccdbbcd287ea26000d14dabaf4365b"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
