name = "Season 6 1.20"
author = "Maple Modworks"
version = "0.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91679c548edf7190eef6b3c843db8c80755e47c6791e3f13143a65fe4e3bf610"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
