name = "Season 6 1.20"
author = "Maple Modworks"
version = "054daa4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b01e42b322b6c1a84c249974aa8cbe295928952a7803f388dff7272f625a25ce"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
