name = "Season 6 1.20"
author = "Maple Modworks"
version = "7a4e029"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e27fc1c83b1c0ab7b7df70931aba9a36e0a924febe0bfe269ce2bc08dff8faa7"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
