name = "Season 6 1.20"
author = "Maple Modworks"
version = "742108c"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78d9e6ca957c7fe297198fddcbe5975a68b68eb474af5176a3059acfde0378bf"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
