name = "Season 6 1.20"
author = "Maple Modworks"
version = "483938b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd5c812a8e2d67c7da8f7e0ecda70ec5180df084e6abfc9342a1c3989d7f6f44"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
