name = "Season 6 1.20"
author = "Maple Modworks"
version = "3be5825"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cb65edda510d999db84ba9588fd9c6666278bffd81ab070564ac97e5fad4627"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
