name = "Season 6 1.20"
author = "Maple Modworks"
version = "07a19c1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0826c2e8b97d47edeb2accba5ddbb27592fbd1d4064fea5fe462187148b10dcf"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
