name = "Season 6 1.20"
author = "Maple Modworks"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56ef543aaab3fc763129b2f46b6f72bc4b87e28c0f3f1e03e451679584edf96c"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
