name = "Season 6 1.20"
author = "Maple Modworks"
version = "b0246d9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fef663a374cc6b54ac8f5218b2adf6f56dd3f3e1afabbc4963dcc606c2b6381"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
