name = "Season 6 1.20"
author = "Maple Modworks"
version = "b0246d9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60b8ff1ed183633744820c358afc01fccdc43b5aebaac828d98c2620a65f9887"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
