name = "Season 6 1.20"
author = "Maple Modworks"
version = "0.0.3 HF 4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ace3675bf1cd758c6a1c6aa22fc4e32f7366b052bade5f3a8aa40517277c32f"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
