name = "Season 6 1.20"
author = "Maple Modworks"
version = "860c73f"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "551cf811661f22dd2d7d83f67d64e580b6f8c31d49eca3294c94005abc3d2a9a"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
