name = "Season 6 1.20"
author = "Maple Modworks"
version = "cadfbd6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c1200257815c7024d93f756353ab49a2e3dc4cc26cac6f4ee402decc09d3744"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
