name = "Season 6 1.20"
author = "Maple Modworks"
version = "019ba58"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9008b81de970a2cf9b8f5662d183def19d23c73b557f183b316d90ee2312b436"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
