name = "Season 6 1.20"
author = "Maple Modworks"
version = "55112d5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e06cefc10af08765bdc0ba2abc9542cecfc136387a3ac78edbef8ddb2bd27b07"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
