name = "Season 6 1.20"
author = "Maple Modworks"
version = "6886efb"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "410e8c91bf5ef41e73e5d659746927431c0631975fa2d5111b2c488daf06a2ac"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
