name = "Season 6 1.20"
author = "Maple Modworks"
version = "0.0.4 HF 1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43563040b7e8924bd3392f23cfdac4eff8e98c4e7b738b3b4183a00da33bbd58"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
