name = "Create-Ive Cogs Season 6"
author = "Canada_LaVearn and Herr Katze"
version = "0.0.9 BYG TEST"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8e91865e2aa56cca260ca073410cbc854d9b4857db529e1cfe584716d36fa11"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
