name = "Season 6 1.20"
author = "Maple Modworks"
version = "32541d9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16a34b63f3d06663545e34c828d56bc6e1f695d54a7db36be349d4e8e7fa7794"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
