name = "Season 6 1.20"
author = "Maple Modworks"
version = "0.0.8 HF 1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42f1c93e5e57d45540bffb3144c06a42df3a428219d373360802f6b4bba7b229"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
