name = "Season 6 1.20"
author = "Maple Modworks"
version = "3fca0ee"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e84b4473006defd23ce8910e4fdd8859f5d55b7f97841c368b52725144fd0489"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
