name = "Season 6 1.20"
author = "Maple Modworks"
version = "55112d5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b55ae65f2657d9d0307fa3dbcc93ac783688e357e0866cabdeaae540f2d9fb78"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
