name = "Season 6 1 20"
author = "Maple Modworks"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a5c6f931138de26deff0081fc4fb59058b7de11a31b04436c46fed716b8a95a"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
