name = "Season 6 1 20"
author = "Maple Modworks"
version = "0.0.1 HF 5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "364675d93f67269daae9272be2bf329c8a61f7eee1e8b1c2826755782c03828a"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
