name = "Season 6 1 20"
author = "Maple Modworks"
version = "0.0.1 HF 2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09eb44ece2ca2a6c6e4eed7dce0b7df816f4f5516716d0c861338044957d101a"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
