name = "Season 6 1.20"
author = "Maple Modworks"
version = "0.0.2 HF 3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93fab8b16c08cc2d7835cb4abab517d7eb8871330ebcf5b164da286f061fe15a"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
