name = "Season 6 1 20"
author = "Maple Modworks"
version = "0.0.1 HF 1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a2de5f6de41b5d244bbeb8f7859266f7e76218bc0133dfc01aaa2013b1f34f7"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
