name = "Season 6 1 20"
author = "Maple Modworks"
version = "0.0.1 HF 4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c62d3f4d2bec64964bb3c482cdfa732a8be0e820bce76296c0185cdbf07ee86"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
